import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const RalewayMedium = localFont({
  src: "./fonts/Raleway-Medium.ttf",
  variable: "--font-Raleway-Medium",
  weight: "100 900",
});
const Raleway = localFont({
  src: "./fonts/Raleway-Regular.ttf",
  variable: "--font-Raleway",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-buy",
  description: "Generated by next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RalewayMedium.variable} ${Raleway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
