import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"], weight: ["400", "500", "700"] , adjustFontFallback: false});
export const metadata: Metadata = {
  title: "E-buy",
  description: "Generated by next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{fontFamily: `${raleway.style.fontFamily}`}}
      >
        {children}
      </body>
    </html>
  );
}
